name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repo structure
        run: ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Find gradlew
        id: find_gradlew
        run: |
          echo "Searching for gradlew..."
          GRAD=$(find . -name gradlew -type f | head -n 1 || true)
          echo "found_gradlew=$GRAD" >> $GITHUB_OUTPUT

      - name: Build with gradlew if present
        if: steps.find_gradlew.outputs.found_gradlew != ''
        run: |
          chmod +x "${{ steps.find_gradlew.outputs.found_gradlew }}"
          DIR=$(dirname "${{ steps.find_gradlew.outputs.found_gradlew }}")
          echo "Running wrapper in $DIR"
          pushd "$DIR"
          ./gradlew :app:assembleDebug
          popd

      - name: Or build with Gradle action if no gradlew
        if: steps.find_gradlew.outputs.found_gradlew == ''
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ":app:assembleDebug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: '**/app/build/outputs/apk/debug/*.apk'
