name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repo structure (debug)
        run: ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle action (no gradlew required)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.0.2'
          arguments: ':app:assembleDebug'

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: '**/app/build/outputs/apk/debug/*.apk'
